// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace RoRSkinBuilder
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using RoRSkinBuilder.Data;
    using UnityEngine.Rendering;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class PluginCodeTemplate : PluginCodeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"using BepInEx;
using BepInEx.Logging;
using RoR2;
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using UnityEngine;
using System.Security;
using System.Security.Permissions;
using MonoMod.RuntimeDetour;

#pragma warning disable CS0618 // Type or member is obsolete
[module: UnverifiableCode]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
#pragma warning restore CS0618 // Type or member is obsolete
[assembly: R2API.Utils.ManualNetworkRegistration]
[assembly: EnigmaticThunder.Util.ManualNetworkRegistration]
namespace ");
            
            #line 26 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.uccModName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 28 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var dependency in DistinctDependencies) { 
            
            #line default
            #line hidden
            this.Write("    [BepInDependency(\"");
            
            #line 29 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dependency.Key));
            
            #line default
            #line hidden
            this.Write("\", BepInDependency.DependencyFlags.");
            
            #line 29 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Enum.GetName(typeof(DependencyType), dependency.Value)));
            
            #line default
            #line hidden
            this.Write(")]\r\n");
            
            #line 30 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    \r\n    [BepInPlugin(\"com.");
            
            #line 32 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SkinModInfo.author));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 32 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.uccModName));
            
            #line default
            #line hidden
            this.Write("\",\"");
            
            #line 32 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SkinModInfo.modName));
            
            #line default
            #line hidden
            this.Write("\",\"");
            
            #line 32 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SkinModInfo.version));
            
            #line default
            #line hidden
            this.Write("\")]\r\n    public partial class ");
            
            #line 33 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.uccModName));
            
            #line default
            #line hidden
            this.Write("Plugin : BaseUnityPlugin\r\n    {\r\n        internal static ");
            
            #line 35 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.uccModName));
            
            #line default
            #line hidden
            this.Write("Plugin Instance { get; private set; }\r\n        internal static ManualLogSource In" +
                    "stanceLogger { get; private set; }\r\n        \r\n        private static AssetBundle" +
                    " assetBundle;\r\n");
            
            #line 39 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (AssetsInfo.materialsWithRoRShader.Count != 0) { 
            
            #line default
            #line hidden
            this.Write("        private static readonly List<Material> materialsWithRoRShader = new List<" +
                    "Material>();\r\n");
            
            #line 41 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        private void Awake()\r\n        {\r\n            Instance = this;\r\n          " +
                    "  BeforeAwake();\r\n            using (var assetStream = Assembly.GetExecutingAsse" +
                    "mbly().GetManifestResourceStream(\"");
            
            #line 46 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.uccModName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 46 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.assetBundleName));
            
            #line default
            #line hidden
            this.Write(@"""))
            {
                assetBundle = AssetBundle.LoadFromStream(assetStream);
            }

            BodyCatalog.availability.CallWhenAvailable(BodyCatalogInit);
            new Hook(typeof(Language).GetMethod(nameof(Language.LoadStrings)), (Action<Action<Language>, Language>)LanguageLoadStrings).Apply();

            ReplaceShaders();

            AfterAwake();
        }

        partial void BeforeAwake();
        partial void AfterAwake();
        static partial void BeforeBodyCatalogInit();
        static partial void AfterBodyCatalogInit();

        private static void ReplaceShaders()
        {
");
            
            #line 66 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var material in AssetsInfo.materialsWithRoRShader) { 
            
            #line default
            #line hidden
            this.Write("            materialsWithRoRShader.Add(LoadMaterialWithReplacedShader(@\"");
            
            #line 67 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.materialPaths[material.Key]));
            
            #line default
            #line hidden
            this.Write("\", @\"");
            
            #line 67 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(material.Value));
            
            #line default
            #line hidden
            this.Write("\"));\r\n");
            
            #line 68 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"        }

        private static Material LoadMaterialWithReplacedShader(string materialPath, string shaderName)
        {
            var material = assetBundle.LoadAsset<Material>(materialPath);
            material.shader = Shader.Find(shaderName);

            return material;
        }

        private static void LanguageLoadStrings(Action<Language> orig, Language self)
        {
            orig(self);

");
            
            #line 83 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 var tokensByLanguage = new Dictionary<string, KeyValuePair<string, List<string>>>();
var defaultTokens = new Dictionary<string, string>();

foreach (var skin in ReorderedSkins) {
    if (skin.nameTokenLocalizations.Count == 0) {
        continue;
    }
    var nameToken = skin.CreateNameToken(SkinModInfo.author);
    defaultTokens[nameToken] = (skin.nameTokenLocalizations.FirstOrDefault(el => el.language.ToLower() == "en") ?? skin.nameTokenLocalizations.First()).value; 
    
    foreach (var localization in skin.nameTokenLocalizations) {
        var language = localization.language.ToLower();
        if (!tokensByLanguage.TryGetValue(language, out var tokens)) {
            tokensByLanguage[language] = tokens = new KeyValuePair<string, List<string>>(nameToken, new List<string>());
        }
        tokens.Value.Add(localization.value);
    } 
} 
            
            #line default
            #line hidden
            this.Write("            switch(self.name.ToLower())\r\n            {\r\n");
            
            #line 103 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var row in tokensByLanguage) { 
            
            #line default
            #line hidden
            this.Write("                case \"");
            
            #line 104 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row.Key));
            
            #line default
            #line hidden
            this.Write("\":\r\n");
            
            #line 105 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
     foreach (var value in row.Value.Value) { 
            
            #line default
            #line hidden
            this.Write("                    self.SetStringByToken(\"");
            
            #line 106 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row.Value.Key));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 106 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(value));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 107 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
     } 
            
            #line default
            #line hidden
            this.Write("                    break;\r\n");
            
            #line 109 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                default:\r\n");
            
            #line 111 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var row in defaultTokens) { 
            
            #line default
            #line hidden
            this.Write("                    self.SetStringByToken(\"");
            
            #line 112 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row.Key));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 112 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(row.Value));
            
            #line default
            #line hidden
            this.Write("\");\r\n                    break;\r\n");
            
            #line 114 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            }
        }

        private static void Nothing(Action<SkinDef> orig, SkinDef self)
        {

        }

        private static void BodyCatalogInit()
        {
            BeforeBodyCatalogInit();

            var hook = new Hook(typeof(SkinDef).GetMethod(nameof(SkinDef.Awake), BindingFlags.NonPublic | BindingFlags.Instance), (Action<Action<SkinDef>, SkinDef>)Nothing);
            hook.Apply();

");
            
            #line 130 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var skin in ReorderedSkins) { 
            
            #line default
            #line hidden
            this.Write("            Add");
            
            #line 131 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.bodyName.ToUpperCamelCase()));
            
            #line default
            #line hidden
            
            #line 131 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.name.ToUpperCamelCase()));
            
            #line default
            #line hidden
            this.Write("Skin();\r\n");
            
            #line 132 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            hook.Undo();\r\n\r\n            AfterBodyCatalogInit();\r\n        }\r\n");
            
            #line 138 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var skin in ReorderedSkins) { 
            
            #line default
            #line hidden
            this.Write("\r\n        static partial void ");
            
            #line 140 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.bodyName.ToUpperCamelCase()));
            
            #line default
            #line hidden
            
            #line 140 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.name.ToUpperCamelCase()));
            
            #line default
            #line hidden
            this.Write("SkinAdded(SkinDef skinDef, GameObject bodyPrefab);\r\n\r\n        private static void" +
                    " Add");
            
            #line 142 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.bodyName.ToUpperCamelCase()));
            
            #line default
            #line hidden
            
            #line 142 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.name.ToUpperCamelCase()));
            
            #line default
            #line hidden
            this.Write("Skin()\r\n        {\r\n");
            
            #line 144 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (!string.IsNullOrWhiteSpace(skin.modDependency.value) && skin.modDependency.type == DependencyType.SoftDependency) { 
            
            #line default
            #line hidden
            this.Write("            if (!BepInEx.Bootstrap.Chainloader.PluginInfos.ContainsKey(\"");
            
            #line 145 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.modDependency.value));
            
            #line default
            #line hidden
            this.Write("\"))\r\n            {\r\n                return;\r\n            }\r\n");
            
            #line 149 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            var bodyName = \"");
            
            #line 150 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.bodyName));
            
            #line default
            #line hidden
            this.Write("\";\r\n            var skinName = \"");
            
            #line 151 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.name));
            
            #line default
            #line hidden
            this.Write(@""";
            try
            {
                var bodyPrefab = BodyCatalog.FindBodyPrefab(bodyName);
                var modelLocator = bodyPrefab.GetComponent<ModelLocator>();
                var mdl = modelLocator.modelTransform.gameObject;
                var skinController = mdl.GetComponent<ModelSkinController>();

");
            
            #line 159 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 switch (skin.renderersSource)
{
    case RenderersSource.AllRendererComponents: 
            
            #line default
            #line hidden
            this.Write("                var renderers = mdl.GetComponentsInChildren<Renderer>(true);\r\n");
            
            #line 163 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
      break;
    case RenderersSource.BaseRendererInfos: 
            
            #line default
            #line hidden
            this.Write("                var characterModel = mdl.GetComponent<CharacterModel>();\r\n       " +
                    "         var renderers = characterModel.baseRendererInfos.Select(info => info.re" +
                    "nderer).ToArray();\r\n");
            
            #line 167 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
      break;
} 
            
            #line default
            #line hidden
            this.Write("\r\n                var skin = ScriptableObject.CreateInstance<SkinDef>();\r\n");
            
            #line 171 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (!skin.icon.createFromColors) {
        if (skin.icon.sprite) { 
            
            #line default
            #line hidden
            this.Write("                skin.icon = assetBundle.LoadAsset<Sprite>(@\"");
            
            #line 173 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.iconPaths[skin.icon.sprite]));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 174 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
      } else { 
            
            #line default
            #line hidden
            this.Write("                skin.icon = null;\r\n");
            
            #line 176 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
      } 
    } else { 
            
            #line default
            #line hidden
            this.Write("                skin.icon = assetBundle.LoadAsset<Sprite>(@\"");
            
            #line 178 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.iconFromColorPaths[skin.icon.colors]));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 179 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                skin.name = skinName;\r\n                skin.nameToken = \"");
            
            #line 181 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.CreateNameToken(SkinModInfo.author)));
            
            #line default
            #line hidden
            this.Write("\";\r\n                skin.rootObject = mdl;\r\n");
            
            #line 183 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (skin.baseSkins.Count == 0) { 
            
            #line default
            #line hidden
            this.Write("                skin.baseSkins = Array.Empty<SkinDef>();\r\n");
            
            #line 185 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                skin.baseSkins = new SkinDef[] \r\n                { \r\n");
            
            #line 188 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var reference in skin.baseSkins) { 
    if (reference.accessType == AccessType.ByIndex) { 
            
            #line default
            #line hidden
            this.Write("                    skinController.skins[");
            
            #line 190 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.index));
            
            #line default
            #line hidden
            this.Write("],\r\n");
            
            #line 191 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                    skinController.skins.First(s => s.Name == \"");
            
            #line 192 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(reference.name));
            
            #line default
            #line hidden
            this.Write("\")\r\n");
            
            #line 193 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
} 
            
            #line default
            #line hidden
            this.Write("                };\r\n");
            
            #line 196 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
if (string.IsNullOrWhiteSpace(skin.unlockableName)) { 
            
            #line default
            #line hidden
            this.Write("                skin.unlockableDef = null;\r\n");
            
            #line 199 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                skin.unlockableDef = ContentManager.UnlockableDef.FirstOrDefault(" +
                    "def => def.cachedName == \"");
            
            #line 200 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.unlockableName));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 201 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 }
if (skin.gameObjectActivations.Count == 0) { 
            
            #line default
            #line hidden
            this.Write("                skin.gameObjectActivations = Array.Empty<SkinDef.GameObjectActiva" +
                    "tion>();\r\n");
            
            #line 204 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                skin.gameObjectActivations = new SkinDef.GameObjectActivation[]\r\n" +
                    "                {\r\n");
            
            #line 207 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var activation in skin.gameObjectActivations) { 
            
            #line default
            #line hidden
            this.Write("                    new SkinDef.GameObjectActivation\r\n                    {\r\n    " +
                    "                    gameObject = renderers[");
            
            #line 210 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(activation.rendererIndex));
            
            #line default
            #line hidden
            this.Write("].gameObject,\r\n                        shouldActivate = ");
            
            #line 211 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (activation.shouldActivate) 
            
            #line default
            #line hidden
            this.Write("true\r\n");
            
            #line 212 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 else 
            
            #line default
            #line hidden
            this.Write("false\r\n                    },\r\n");
            
            #line 214 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                };\r\n");
            
            #line 216 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
if (skin.rendererInfos.Count == 0) { 
            
            #line default
            #line hidden
            this.Write("                skin.rendererInfos = Array.Empty<CharacterModel.RendererInfo>();\r" +
                    "\n");
            
            #line 219 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                skin.rendererInfos = new CharacterModel.RendererInfo[]\r\n         " +
                    "       {\r\n");
            
            #line 222 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var rendererInfo in skin.rendererInfos) { 
            
            #line default
            #line hidden
            this.Write("                    new CharacterModel.RendererInfo\r\n                    {\r\n");
            
            #line 225 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (rendererInfo.defaultMaterial == null) { 
            
            #line default
            #line hidden
            this.Write("                        defaultMaterial = null,\r\n");
            
            #line 227 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                        defaultMaterial = assetBundle.LoadAsset<Material>(@\"");
            
            #line 228 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.materialPaths[rendererInfo.defaultMaterial]));
            
            #line default
            #line hidden
            this.Write("\"),\r\n");
            
            #line 229 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                        defaultShadowCastingMode = UnityEngine.Rendering.ShadowCa" +
                    "stingMode.");
            
            #line 230 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Enum.GetName(typeof(ShadowCastingMode), rendererInfo.defaultShadowCastingMode)));
            
            #line default
            #line hidden
            this.Write(",\r\n                        ignoreOverlays = ");
            
            #line 231 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (rendererInfo.ignoreOverlays) 
            
            #line default
            #line hidden
            this.Write("true,\r\n");
            
            #line 232 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 else 
            
            #line default
            #line hidden
            this.Write("false,\r\n");
            
            #line 233 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (rendererInfo.rendererReference.accessType == AccessType.ByIndex) { 
            
            #line default
            #line hidden
            this.Write("                        renderer = renderers[");
            
            #line 234 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rendererInfo.rendererReference.index));
            
            #line default
            #line hidden
            this.Write("]\r\n");
            
            #line 235 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                        renderer = renderers.First(r => r.name == \"");
            
            #line 236 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(rendererInfo.rendererReference.name));
            
            #line default
            #line hidden
            this.Write("\")\r\n");
            
            #line 237 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                    },\r\n");
            
            #line 239 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                };\r\n");
            
            #line 241 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 }
if (skin.meshReplacements.Count == 0) { 
            
            #line default
            #line hidden
            this.Write("                skin.meshReplacements = Array.Empty<SkinDef.MeshReplacement>();\r\n" +
                    "");
            
            #line 244 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                skin.meshReplacements = new SkinDef.MeshReplacement[]\r\n          " +
                    "      {\r\n");
            
            #line 247 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var replacement in skin.meshReplacements) { 
            
            #line default
            #line hidden
            this.Write("                    new SkinDef.MeshReplacement\r\n                    {\r\n");
            
            #line 250 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (replacement.mesh == null) { 
            
            #line default
            #line hidden
            this.Write("                        mesh = null,\r\n");
            
            #line 252 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                        mesh = assetBundle.LoadAsset<Mesh>(@\"");
            
            #line 253 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.meshPaths[replacement.mesh]));
            
            #line default
            #line hidden
            this.Write("\"),\r\n");
            
            #line 254 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
if (replacement.rendererReference.accessType == AccessType.ByIndex) { 
            
            #line default
            #line hidden
            this.Write("                        renderer = renderers[");
            
            #line 256 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.rendererReference.index));
            
            #line default
            #line hidden
            this.Write("]\r\n");
            
            #line 257 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                        renderer = renderers.First(r => r.name == \"");
            
            #line 258 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.rendererReference.name));
            
            #line default
            #line hidden
            this.Write("\")\r\n");
            
            #line 259 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                    },\r\n");
            
            #line 261 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                };\r\n");
            
            #line 263 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 }
if (skin.minionSkinReplacements.Count == 0) { 
            
            #line default
            #line hidden
            this.Write("                skin.minionSkinReplacements = Array.Empty<SkinDef.MinionSkinRepla" +
                    "cement>();\r\n");
            
            #line 266 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                skin.minionSkinReplacements = new SkinDef.MinionSkinReplacement[]" +
                    "\r\n                {\r\n");
            
            #line 269 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var replacement in skin.minionSkinReplacements) {
    if (!replacement.findSkinByReference && replacement.skin == null) {
        continue;
    } 
            
            #line default
            #line hidden
            this.Write("                    new SkinDef.MinionSkinReplacement\r\n                    {\r\n   " +
                    "                     minionBodyPrefab = BodyCatalog.FindBodyPrefab(@\"");
            
            #line 275 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.bodyName));
            
            #line default
            #line hidden
            this.Write("\"),\r\n");
            
            #line 276 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (replacement.findSkinByReference) { 
    if (replacement.reference.accessType == AccessType.ByIndex) { 
            
            #line default
            #line hidden
            this.Write("                        minionSkin = BodyCatalog.GetBodySkins(BodyCatalog.FindBod" +
                    "yIndex(@\"");
            
            #line 278 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.bodyName));
            
            #line default
            #line hidden
            this.Write("\"))[");
            
            #line 278 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.reference.index));
            
            #line default
            #line hidden
            this.Write("]\r\n");
            
            #line 279 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                        minionSkin = BodyCatalog.GetBodySkins(BodyCatalog.FindBod" +
                    "yIndex(@\"");
            
            #line 280 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.bodyName));
            
            #line default
            #line hidden
            this.Write("\")).First(s => s.name == @\"");
            
            #line 280 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.reference.name));
            
            #line default
            #line hidden
            this.Write("\")\r\n    ");
            
            #line 281 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 }
} else { 
            
            #line default
            #line hidden
            this.Write("                        minionSkin = BodyCatalog.GetBodySkins(BodyCatalog.FindBod" +
                    "yIndex(@\"");
            
            #line 283 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.bodyName));
            
            #line default
            #line hidden
            this.Write("\")).First(s => s.name == @\"");
            
            #line 283 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.skin.name));
            
            #line default
            #line hidden
            this.Write("\")\r\n");
            
            #line 284 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                    },\r\n");
            
            #line 286 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                };\r\n");
            
            #line 288 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
if (skin.projectileGhostReplacements.Count == 0) { 
            
            #line default
            #line hidden
            this.Write("                skin.projectileGhostReplacements = Array.Empty<SkinDef.Projectile" +
                    "GhostReplacement>();\r\n");
            
            #line 291 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                skin.projectileGhostReplacements = new SkinDef.ProjectileGhostRep" +
                    "lacement[]\r\n                {\r\n");
            
            #line 294 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 foreach (var replacement in skin.projectileGhostReplacements) { 
            
            #line default
            #line hidden
            this.Write("                    new SkinDef.ProjectileGhostReplacement\r\n                    {" +
                    "\r\n                        projectilePrefab = Resources.Load<GameObject>(@\"");
            
            #line 297 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.projectilePath));
            
            #line default
            #line hidden
            this.Write("\"),\r\n");
            
            #line 298 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 if (replacement.useResourcesPath) { 
            
            #line default
            #line hidden
            this.Write("                        projectileGhostReplacementPrefab = Resources.Load<GameObj" +
                    "ect>(@\"");
            
            #line 299 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(replacement.projectileGhostPath));
            
            #line default
            #line hidden
            this.Write("\")\r\n");
            
            #line 300 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("                        projectileGhostReplacementPrefab = assetBundle.LoadAsset<" +
                    "GameObject>(@\"");
            
            #line 301 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AssetsInfo.gameObjectPaths[replacement.projectileGhost]));
            
            #line default
            #line hidden
            this.Write("\")\r\n");
            
            #line 302 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                    },\r\n");
            
            #line 304 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("                };\r\n");
            
            #line 306 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"
                Array.Resize(ref skinController.skins, skinController.skins.Length + 1);
                skinController.skins[skinController.skins.Length - 1] = skin;

                BodyCatalog.skins[(int)BodyCatalog.FindBodyIndex(bodyPrefab)] = skinController.skins;
                ");
            
            #line 312 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.bodyName.ToUpperCamelCase()));
            
            #line default
            #line hidden
            
            #line 312 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(skin.name.ToUpperCamelCase()));
            
            #line default
            #line hidden
            this.Write(@"SkinAdded(skin, bodyPrefab);
            }
            catch (Exception e)
            {
                InstanceLogger.LogWarning($""Failed to add \""{skinName}\"" skin to \""{bodyName}\"""");
                InstanceLogger.LogError(e);
            }
        }
");
            
            #line 320 "C:\Users\Admin\Desktop\F\RoR2 Modding\RoRSkinModCreator\RoRSkinModCreator\CodeGeneration\PluginCodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"    }

}

namespace R2API.Utils
{
    [AttributeUsage(AttributeTargets.Assembly)]
    public class ManualNetworkRegistrationAttribute : Attribute { }
}

namespace EnigmaticThunder.Util
{
    [AttributeUsage(AttributeTargets.Assembly)]
    public class ManualNetworkRegistrationAttribute : Attribute { }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
